
lambda_data = zeros(Result.NUM,num_group);
SLs_data = zeros(Result.NUM,num_group);
Sort_gamma_data = cell(Result.NUM,num_group);
for j = 1:Result.NUM
    lambda_data(j,:) = IterationHistory(j).lambda_star;
    SLs_data(j,:) = IterationHistory(j).SLs;
    Sort_gamma_data(j,:) = IterationHistory(j).Sort_gamma;
end 

% Create color 
colors = [0.3, 0.5, 0.84; 0.20, 0.66, 0.97]; 

for comp = 1:num_group
    figure  
    lambda_comp = lambda_data(:, comp);
    SLs_comp = SLs_data(:, comp);

    h_iter = plot(lambda_comp, SLs_comp, ...
        'Color', colors(comp, :), ...
        'LineWidth', 2, ...
        'Marker', 'o', ...
        'MarkerSize', 4, ...
        'MarkerFaceColor', 'w',...
        'DisplayName', 'Trajectory');
    hold on;

    % Mark each iteration point
    x_offset = (max(lambda_comp) - min(lambda_comp)) ;
    y_offset = (max(SLs_comp) - min(SLs_comp));

    iter = 1;
    plot(lambda_comp(iter) + 0.05*x_offset, SLs_comp(iter) + 0.03*y_offset, 'ko', ...
        'MarkerSize', 14, ...
        'MarkerFaceColor', 'w', ...
        'LineWidth', 1);
    text(lambda_comp(iter) + 0.05*x_offset, SLs_comp(iter) + 0.03*y_offset, ...
        sprintf('%d', iter), ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'Color', 'k', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle');

    iter = 2;
    plot(lambda_comp(iter) + 0.04*x_offset, SLs_comp(iter) + 0.05*y_offset, 'ko', ...
        'MarkerSize', 14, ...
        'MarkerFaceColor', 'w', ...
        'LineWidth', 1);
    text(lambda_comp(iter) + 0.04*x_offset, SLs_comp(iter) + 0.05*y_offset, ...
        sprintf('%d', iter), ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'Color', 'k', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle');

    iter = 3;
    plot(lambda_comp(iter) + 0.005*x_offset, SLs_comp(iter) + 0.075*y_offset, 'ko', ...
        'MarkerSize', 14, ...
        'MarkerFaceColor', 'w', ...
        'LineWidth', 1);
    text(lambda_comp(iter) + 0.005*x_offset, SLs_comp(iter) + 0.075*y_offset, ...
        sprintf('%d', iter), ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'Color', 'k', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle');

    iter = 4;
    plot(lambda_comp(iter) + 0.02*x_offset, SLs_comp(iter) + 0.07*y_offset, 'ko', ...
        'MarkerSize', 14, ...
        'MarkerFaceColor', 'w', ...
        'LineWidth', 1);
    text(lambda_comp(iter) + 0.02*x_offset, SLs_comp(iter) + 0.07*y_offset, ...
        sprintf('%d', iter), ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'Color', 'k', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle');

    iter = 5;
    plot(lambda_comp(iter) + 0.04*x_offset, SLs_comp(iter) + 0.04*y_offset, 'ko', ...
        'MarkerSize', 14, ...
        'MarkerFaceColor', 'w', ...
        'LineWidth', 1);
    text(lambda_comp(iter) + 0.04*x_offset, SLs_comp(iter) + 0.04*y_offset, ...
        sprintf('%d', iter), ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'Color', 'k', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle');

    iter = 6;
    plot(lambda_comp(iter) + 0.05*x_offset, SLs_comp(iter) - 0.001*y_offset, 'ko', ...
        'MarkerSize', 14, ...
        'MarkerFaceColor', 'w', ...
        'LineWidth', 1);
    text(lambda_comp(iter) + 0.05*x_offset, SLs_comp(iter) - 0.001*y_offset, ...
        sprintf('%d', iter), ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'Color', 'k', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle');

    iter = 7;
    plot(lambda_comp(iter) + 0.05*x_offset, SLs_comp(iter) + 0.06*y_offset, 'ko', ...
        'MarkerSize', 14, ...
        'MarkerFaceColor', 'w', ...
        'LineWidth', 1);
    text(lambda_comp(iter) + 0.05*x_offset, SLs_comp(iter) + 0.06*y_offset, ...
        sprintf('%d', iter), ...
        'FontSize', 13, 'FontWeight', 'bold', ...
        'Color', 'k', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle');
    
    % Mark iteration 1
    h_initial = plot(lambda_comp(1), SLs_comp(1), 'r^', ...
        'MarkerSize', 7,'MarkerFaceColor', 'r', 'LineWidth', 1.5,...
        'DisplayName', 'Iter1');

    % Mark iteration Result.NUM (final state)
    h_final = plot(lambda_comp(end), SLs_comp(end), 'rv', ...
        'MarkerSize', 7, 'MarkerFaceColor', 'r', 'LineWidth', 1.5,...
        'DisplayName', sprintf('Iter%d (Final)', Result.NUM));

    % Add target line 
    target_SLs = paraFPPA.TargetTSLs;
    h_target = yline(target_SLs(comp), 'r--', 'LineWidth', 1.5, 'Alpha', 0.7,...
        'DisplayName', sprintf('Target(%d)', target_SLs(comp)));

    % Calculate the gap between final state and target
    distance_to_target = abs(SLs_comp(end) - target_SLs(comp));

    % Set graph properties
    xlabel(sprintf('λ_{%d}', comp), 'FontSize', 8);
    ylabel(sprintf('SL'), 'FontSize', 8);
    ax = gca;
    ax.FontSize = 16;

    title({sprintf('λ_{%d}: %.4e → %.4e',comp, lambda_comp(1), lambda_comp(end)), ...
           sprintf('SL: %d → %d', SLs_comp(1), SLs_comp(end))}, ...
                   'FontSize', 14);
    grid on;

    % Set axis ranges
    xlim([min(lambda_comp), max(lambda_comp)]);
    ylim([min([SLs_comp; target_SLs(comp)]), max([SLs_comp; target_SLs(comp)])]);
    current_xlim = xlim;
    current_ylim = ylim;
    x_range_total = current_xlim(2) - current_xlim(1);
    y_range_total = current_ylim(2) - current_ylim(1);
    xlim([current_xlim(1) - x_range_total * 0.1, current_xlim(2) + x_range_total * 0.1]);
    ylim([current_ylim(1) - y_range_total * 0.1, current_ylim(2) + y_range_total * 0.1]);

    legend([h_iter,h_initial, h_final, h_target], ...
        'Location', 'southwest', 'FontSize', 10);
end

%% figure
figure
colors = lines(Result.NUM);
h_lines = gobjects(Result.NUM, 1);
final_sg = IterationHistory(Result.NUM).Sort_gamma{1};
for iter = 1:Result.NUM
    current_sg = IterationHistory(iter).Sort_gamma{1};
    x_values = 1:length(current_sg);
    if iter == Result.NUM
        diff = zeros(size(current_sg));
    else
        diff = abs(current_sg - final_sg);
    end    
    h = semilogy(x_values, diff, ...
        'Color', colors(iter, :), ...
        'LineWidth', 1.5, ...
        'DisplayName', sprintf('k = %d', iter));
    h_lines(iter) = h;
    hold on;
end

xlabel('Index', 'FontSize', 12);
ylabel('$|\gamma_{1,i_s^k}(\mathbf{u}^k)-\gamma_{1,i_s}(\mathbf{u}^7)|$', 'FontSize', 12, ...
    'Interpreter', 'latex','FontWeight', 'bold', ...
    'Color', [0, 0, 0]);
ax = gca;
ax.FontSize = 16;
grid on;
legend(h_lines(1:end-1,:), 'Location', 'southwest', 'FontSize', 12,'NumColumns', 2);
title('Difference from $\gamma_{1,i_s}(\mathbf{u}^7)$ Values', 'FontSize', 16, 'Interpreter', 'latex', 'FontWeight', 'bold');

figure
colors = lines(Result.NUM);
h_lines = gobjects(Result.NUM, 1);
final_sg = IterationHistory(Result.NUM).Sort_gamma{2};
for iter = 1:Result.NUM
    current_sg = IterationHistory(iter).Sort_gamma{2};
    x_values = 1:length(current_sg);
    if iter == Result.NUM
        diff = zeros(size(current_sg));
    else
        diff = abs(current_sg - final_sg);
    end    
    h = semilogy(x_values, diff, ...
        'Color', colors(iter, :), ...
        'LineWidth', 1.5, ...
        'DisplayName', sprintf('k = %d', iter));
    h_lines(iter) = h;
    hold on;
end

xlabel('Index', 'FontSize', 12);
ylabel('$|\gamma_{2,i_s^k}(\mathbf{u}^k)-\gamma_{2,i_s}(\mathbf{u}^7)|$', 'FontSize', 12, ...
    'Interpreter', 'latex','FontWeight', 'bold', ...
    'Color', [0, 0, 0]);
ax = gca;
ax.FontSize = 16;
grid on;
legend(h_lines(1:end-1,:), 'Location', 'southwest', 'FontSize', 12,'NumColumns', 2);
title('Difference from $\gamma_{2,i_s}(\mathbf{u}^7)$ Values', 'FontSize', 16, 'Interpreter', 'latex', 'FontWeight', 'bold');


